

export function generateHouseNumber():string{
	const houseNumber = Math.floor(Math.random() * 200);
	return String(houseNumber);
}

export function generatePostcode():string{
	const letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
	const numbers = "0123456789";
	const outward = `${letters[Math.floor(Math.random() * 26)]}${letters[Math.floor(Math.random() * 26)]}${numbers[Math.floor(Math.random() * 10)]}`;
	const inward = `${numbers[Math.floor(Math.random() * 10)]}${letters[Math.floor(Math.random() * 26)]}${letters[Math.floor(Math.random() * 26)]}`;
	return `${outward} ${inward}`;
}

export function generateCounty():string{
	const randomCounty = ukCounties[Math.floor(Math.random() * ukCounties.length)];
	return randomCounty;
}

export function generateStreetName():string{
	const randomStreenPrefix = ukStreetPrefixes[Math.floor(Math.random() * ukStreetPrefixes.length)];
	const randomStreenSuffix = ukStreetSuffixes[Math.floor(Math.random() * ukStreetSuffixes.length)];
	return `${randomStreenPrefix} ${randomStreenSuffix}`;
}

export function generateRandomVillage():string{
	const randomVillage = ukVillages[Math.floor(Math.random() * ukVillages.length)];
	return randomVillage;
}

export function generateTown():string{
	const randomTown = ukTowns[Math.floor(Math.random() * ukTowns.length)];
	return randomTown;
}

const ukCounties:string[] = [
	"Aberdeenshire",
	"Angus",
	"Argyllshire",
	"Ayrshire",
	"Banffshire",
	"Bedfordshire",
	"Berkshire",
	"Berwickshire",
	"Buckinghamshire",
	"Caithness",
	"Cambridgeshire",
	"Cheshire",
	"Clackmannanshire",
	"Cornwall",
	"Cromartyshire",
	"Cumberland",
	"Cumbria",
	"Denbighshire",
	"Derbyshire",
	"Devon",
	"Dorset",
	"Dumfriesshire",
	"Dunbartonshire",
	"Durham",
	"East Lothian",
	"Essex",
	"Fife",
	"Flintshire",
	"Glamorgan",
	"Gloucestershire",
	"Hampshire",
	"Herefordshire",
	"Hertfordshire",
	"Inverness-shire",
	"Isle of Wight",
	"Kent",
	"Kincardineshire",
	"Kinross-shire",
	"Kirkcudbrightshire",
	"Lanarkshire",
	"Lancashire",
	"Leicestershire",
	"Lincolnshire",
	"London",
	"Merioneth",
	"Merseyside",
	"Midlothian",
	"Monmouthshire",
	"Montgomeryshire",
	"Morayshire",
	"Nairnshire",
	"Norfolk",
	"Northamptonshire",
	"Northumberland",
	"Nottinghamshire",
	"Orkney",
	"Oxfordshire",
	"Peeblesshire",
	"Pembrokeshire",
	"Perthshire",
	"Radnorshire",
	"Renfrewshire",
	"Ross-shire",
	"Roxburghshire",
	"Rutland",
	"Selkirkshire",
	"Shetland",
	"Shropshire",
	"Somerset",
	"Staffordshire",
	"Stirlingshire",
	"Suffolk",
	"Surrey",
	"Sussex",
	"Sutherland",
	"Tyne and Wear",
	"Warwickshire",
	"West Lothian",
	"West Midlands",
	"Westmorland",
	"Wigtownshire",
	"Wiltshire",
	"Worcestershire",
	"Yorkshire"
];

const ukStreetSuffixes:string[] = [
	"Avenue",
	"Boulevard",
	"Close",
	"Crescent",
	"Drive",
	"Gardens",
	"Gate",
	"Grove",
	"Hill",
	"Lane",
	"Mews",
	"Park",
	"Place",
	"Road",
	"Row",
	"Square",
	"Street",
	"Terrace",
	"Walk",
	"Way",
	"Alley",
	"Arcade",
	"Circle",
	"Court",
	"Hillside",
	"Lodge",
	"Path",
	"Pathway",
	"Passage",
	"Place",
	"Ridge",
	"Rise",
	"Stairs",
	"Trail",
	"Villas",
	"Wharf",
	"Yard",
	"Abbey",
	"Bank",
	"Bar",
	"Barn",
	"Bridge",
	"Camp",
	"Castle",
	"Center",
	"Chase",
	"Church",
	"Corner",
	"Crossing",
	"Depot",
	"Docks",
	"Factory",
	"Field",
	"Forest",
	"Forge",
	"Foundry",
	"Gardens",
	"Harbor",
	"Haven",
	"Heights",
	"Junction",
	"Knoll",
	"Landing",
	"Market",
	"Mill",
	"Orchard",
	"Palace",
	"Parade",
	"Pass",
	"Plantation",
	"Plaza",
	"Port",
	"Promenade",
	"Quay",
	"Reserve",
	"Riverside",
	"Shore",
	"Siding",
	"Spur",
	"Station",
	"Subdivision",
	"Summit",
	"Terrace",
	"Track",
	"Turnpike",
	"Vale",
	"Viaduct",
	"View",
	"Village",
	"Vineyard",
	"Woods"
];

const ukStreetPrefixes:string[] = [
	"High",
	"Baker",
	"King",
	"Queen",
	"Market",
	"Church",
	"Main",
	"Park",
	"Green",
	"Mill",
	"Bridge",
	"Orchard",
	"Sycamore",
	"Elm",
	"Willow",
	"Oak",
	"Chestnut",
	"Maple",
	"Grove",
	"Hill",
	"Meadow",
	"Walnut",
	"Cherry",
	"Pine",
	"Cedar",
	"Aspen",
	"Birch",
	"Holly",
	"Magnolia",
	"Spring",
	"Summer",
	"Autumn",
	"Winter",
	"Sunset",
	"Dawn",
	"Dusk",
	"Riverside",
	"Lakeside",
	"Water",
	"Canal",
	"Garden",
	"Heath",
	"Forest",
	"Woodland",
	"Paddock",
	"Fern",
	"Moor",
	"Valley",
	"Coast",
	"Cliff",
	"Harbor",
	"Beach",
	"Marina",
	"Cove",
	"Bay",
	"Seaside",
	"Ocean",
	"Sea",
	"Wave",
	"Coral",
	"Pearl",
	"Anchor",
	"Sail",
	"Mermaid",
	"Lighthouse",
	"Compass",
	"Explorer",
	"Voyage",
	"Discovery",
	"Adventure",
	"Pioneer",
	"Heritage",
	"Legacy",
	"Victory",
	"Liberty",
	"Freedom",
	"Peace",
	"Hope",
	"Dream",
	"Love",
	"Harmony",
	"Unity",
	"Tranquility",
	"Serenity",
	"Prosperity",
	"Felicity",
	"Happiness",
	"Joy",
	"Bliss",
	"Grace",
	"Elegance"
]

const ukTowns:string[] = [
	"Aberdeen",
	"Armagh",
	"Bangor",
	"Bath",
	"Belfast",
	"Birmingham",
	"Blackburn",
	"Blackpool",
	"Bolton",
	"Bournemouth",
	"Bradford",
	"Brighton",
	"Bristol",
	"Cambridge",
	"Canterbury",
	"Cardiff",
	"Carlisle",
	"Chelmsford",
	"Cheltenham",
	"Chester",
	"Chichester",
	"Coventry",
	"Crawley",
	"Croydon",
	"Darlington",
	"Derby",
	"Derry",
	"Doncaster",
	"Dover",
	"Dundee",
	"Durham",
	"Eastbourne",
	"Edinburgh",
	"Ely",
	"Exeter",
	"Falmouth",
	"Gateshead",
	"Glasgow",
	"Gloucester",
	"Grimsby",
	"Guildford",
	"Halifax",
	"Harrow",
	"Hastings",
	"Hemel Hempstead",
	"Hereford",
	"Huddersfield",
	"Hull",
	"Inverness",
	"Ipswich",
	"Islington",
	"Kensington",
	"Kettering",
	"Kingston upon Thames",
	"Lancaster",
	"Leeds",
	"Leicester",
	"Lichfield",
	"Lincoln",
	"Lisburn",
	"Liverpool",
	"Londonderry",
	"London",
	"Luton",
	"Manchester",
	"Middlesbrough",
	"Milton Keynes",
	"Newcastle upon Tyne",
	"Newport",
	"Newry",
	"Northampton",
	"Norwich",
	"Nottingham",
	"Oxford",
	"Paisley",
	"Penzance",
	"Perth",
	"Peterborough",
	"Plymouth",
	"Poole",
	"Portsmouth",
	"Preston",
	"Reading",
	"Redditch",
	"Ripon",
	"Rochdale",
	"Rotherham",
	"Salford",
	"Salisbury",
	"Scarborough",
	"Scunthorpe",
	"Sheffield",
	"Shrewsbury",
	"Slough",
	"Solihull",
	"Southampton",
	"Southend-on-Sea",
	"Southport",
	"St Albans",
	"St Asaph",
	"St Davids",
	"Stirling",
	"Stoke-on-Trent",
	"Sunderland",
	"Sutton Coldfield",
	"Swansea",
	"Swindon",
	"Taunton",
	"Telford",
	"Torquay",
	"Truro",
	"Wakefield",
	"Walsall",
	"Warrington",
	"Warwick",
	"Watford",
	"Wells",
	"Westminster",
	"Weymouth",
	"Wigan",
	"Winchester",
	"Windsor",
	"Wolverhampton",
	"Worcester",
	"Worthing",
	"York",
	]

const ukVillages = [
	"Aberlady",
	"Aldbourne",
	"Alfriston",
	"Amberley",
	"Ashford-in-the-Water",
	"Askrigg",
	"Avebury",
	"Bamburgh",
	"Barningham",
	"Beaulieu",
	"Berrynarbor",
	"Bibury",
	"Birlingham",
	"Blanchland",
	"Blockley",
	"Bourton-on-the-Water",
	"Branscombe",
	"Bray",
	"Broadway",
	"Brook",
	"Buckler's Hard",
	"Burley",
	"Burnsall",
	"Cadgwith",
	"Cartmel",
	"Castle Acre",
	"Castle Combe",
	"Cawdor",
	"Chagford",
	"Chilham",
	"Chipping Campden",
	"Clare",
	"Clovelly",
	"Corfe Castle",
	"Cromford",
	"Crosby Ravensworth",
	"Crowcombe",
	"Culross",
	"Dedham",
	"Dorchester-on-Thames",
	"Dovedale",
	"Downham",
	"Easington",
	"Easwald",
	"Edensor",
	"Egton",
	"Elterwater",
	"Eltisley",
	"Eynsford",
	"Falkland",
	"Farningham",
	"Fowey",
	"Framlingham",
	"Gargrave",
	"Grasmere",
	"Great Tew",
	"Hambledon",
	"Hawkshead",
	"Hayfield",
	"Helford",
	"Helmsley",
	"Hovingham",
	"Ilmington",
	"Ingleton",
	"Kettlewell",
	"Kingsand",
	"Lacock",
	"Lavenham",
	"Long Melford",
	"Lower Slaughter",
	"Luss",
	"Mells",
	"Mersea Island",
	"Milton Abbas",
	"Mousehole",
	"Newton-in-Bowland",
	"Orford",
	"Pembridge",
	"Plockton",
	"Polperro",
	"Porlock",
	"Port Isaac",
	"Portmeirion",
	"Prestbury",
	"Ravenglass",
	"Reeth",
	"Rye",
	"Sennen",
	"Shere",
	"Shipton-under-Wychwood",
	"Skipton",
	"Slaidburn",
	"Snowshill",
	"Staithes",
	"Stow-on-the-Wold",
	"Stratford-upon-Avon",
	"Tetbury",
	"Thaxted",
	"Tobermory",
	"Tissington",
	"Ullapool",
	"Upper Slaughter",
	"Warkworth",
	"Wells-next-the-Sea",
	"Westerham",
	"Willingham"
];
