export enum UploadStatuses {
	waiting = "Awaiting Upload",
	uploading = "Upload in Progress",
	uploadFailed = "Upload Failed",
}

export enum LightingType {
	PlinthLighting = "PlinthLighting",
	UnderUnitLighting = "UnderUnitLighting",
	InteriorUnitLighting = "InteriorUnitLighting",
	DrawerLighting = "DrawerLighting",
	MilanoProfileLighting = "MilanoProfileLighting",
}

export enum LightingUnitTypes {
	BaseUnitLighting = "BaseUnitLighting",
	TowerUnitLighting = "TowerUnitLighting",
	IslandUnitLighting = "IslandUnitLighting",
	WallUnitLighting = "WallUnitLighting",
}

export enum LightingSelections {
	LightingType = "LightingType",
	LightingStyle = "LightingStyle",
	LightingColour = "LightingColour",
	LightingProduct = "LightingProduct",
	LightingDiffuser = "LightingDiffuser",
}

export enum RangeScope {
	DefaultRange = "defaultRange",
	BaseRange = "baseRange",
	WallRange = "wallRange",
	TowerRange = "towerRange",
	IslandRange = "islandRange",
	ChestRange = "chestRange",
	WardrobeRange = "wardrobeRange",
	BridgingRange = "bridgingRange",
}

export enum MeasurementEntryType {
	Height = "height",
	Depth = "depth",
	Width = "width",
	Length = "length",
	HeadboardHeight = "headboardHeight",
	HeadboardRequired = "headboardRequired",
	PositiveX = "positiveX",
	PositiveY = "positiveY",
	PositiveZ = "positiveZ",
	NegativeX = "negativeX",
	NegativeY = "negativeY",
	NegativeZ = "negativeZ",
	CeilingHeight = "ceilingHeight",
	SpringLineHeight = "springLineHeight",
	WindowsillDepth = "windowsillDepth",
	HeightFromPeakToFloor = "heightFromPeakToFloor",
	DoorWidth = "doorWidth",
	Distance = "distance",
	CentreWindowWidth = "centreWindowWidth",
	ChimneyBreastSection = "chimneyBreastSection",
	ChimneyBreastAWidth = "chimneyBreastAWidth",
	ChimneyBreastBWidth = "chimneyBreastBWidth",
	ChimneyBreastCWidth = "chimneyBreastCWidth",
	ChimneyBreastBHeightFromFloor = "ChimneyBreastBHeightFromFloor",
	None = "none",
}

export enum SpecialistMaterial {
	Granite = "Granite",
	Quartz = "Quartz",
	Corian = "Corian",
	WrenQuartz = "Wren Quartz",
	Wood = "Wood",
}

export enum NonSpecialistMaterial {
	LuxuryLaminate = "Luxury Laminate",
	Timber = "Timber",
	KLife = "K-Life",
	Laminate = "Laminate",
	RhinoEdge = "Rhino Edge",
	LuxuryBespoke = "Luxury Bespoke",
	LegacyBespoke = "Bespoke",
}


export enum UnitHeight {
	"Height20" = 20,
	"Height114" = 114,
	"Height116" = 116,
	"Height140" = 140,
	"Height145" = 145,
	"Height150" = 150,
	"Height152" = 152,
	"Height165" = 165,
	"Height215" = 215,
	"Height288" = 288,
	"Height304" = 304,
	"Height356" = 356,
	"Height360" = 360,
	"Height380" = 380,
	"Height450" = 450,
	"Height456" = 456,
	"Height496" = 496,
	"Height510" = 510,
	"Height520" = 520,
	"Height528" = 528,
	"Height532" = 532,
	"Height540" = 540,
	"Height550" = 550,
	"Height570" = 570,
	"Height575" = 575,
	"Height576" = 576,
	"Height595" = 595,
	"Height596" = 596,
	"Height608" = 608,
	"Height720" = 720,
	"Height724" = 724,
	"Height725" = 725,
	"Height730" = 730,
	"Height732" = 732,
	"Height735" = 735,
	"Height740" = 740,
	"Height760" = 760,
	"Height836" = 836,
	"Height838" = 838,
	"Height842" = 842,
	"Height867" = 867,
	"Height870" = 870,
	"Height876" = 876,
	"Height879" = 879,
	"Height880" = 880,
	"Height884" = 884,
	"Height900" = 900,
	"Height905" = 905,
	"Height912" = 912,
	"Height926" = 926,
	"Height984" = 984,
	"Height1047" = 1047,
	"Height1055" = 1055,
	"Height1064" = 1064,
	"Height1092" = 1092,
	"Height1162" = 1162,
	"Height1170" = 1170,
	"Height1172" = 1172,
	"Height1180" = 1180,
	"Height1200" = 1200,
	"Height1260" = 1260,
	"Height1285" = 1285,
	"Height1342" = 1342,
	"Height1350" = 1350,
	"Height1355" = 1355,
	"Height1360" = 1360,
	"Height1380" = 1380,
	"Height1475" = 1475,
	"Height1500" = 1500,
	"Height1525" = 1525,
	"Height1535" = 1535,
	"Height1580" = 1580,
	"Height1590" = 1590,
	"Height1592" = 1592,
	"Height1650" = 1650,
	"Height1670" = 1670,
	"Height1672" = 1672,
	"Height1780" = 1780,
	"Height1781" = 1781,
	"Height1900" = 1900,
	"Height2018" = 2018,
	"Height2070" = 2070,
	"Height2075" = 2075,
	"Height2080" = 2080,
	"Height2094" = 2094,
	"Height2100" = 2100,
	"Height2120" = 2120,
	"Height2134" = 2134,
	"Height2191" = 2191,
	"Height2210" = 2210,
	"Height2250" = 2250,
	"Height2260" = 2260,
	"Height2265" = 2265,
	"Height2286" = 2286,
	"Height2343" = 2343,
	"Height2360" = 2360,
	"Height2438" = 2438,
	"Height2495" = 2495,
}

export enum UnitConfiguration {
	Adjustable = "Adjustable",
	ApplianceHideaway = "Appliance Hideaway",
	ApplianceHousing = "Appliance Housing",
	Belfast = "Belfast",
	BelfastSink = "Belfast Sink",
	Boiler = "Boiler",
	BuiltUnderOvenHousing = "Built Under Oven Housing",
	ChestTop = "Chest Top",
	CounterTopSink = "Counter Top Sink",
	Diagonal = "Diagonal",
	Downdraft = "Downdraft",
	Drawer = "Drawer",
	DrawerUnit = "Drawer Unit",
	Extractor = "Extractor",
	Fixed = "Fixed",
	FridgeAndFreezerHousing = "Fridge and Freezer Housing",
	Hob = "Hob",
	InternalCurved = "Internal Curved",
	Kitchen = "Kitchen",
	LShape = "L Shape",
	Microwave = "Microwave",
	ModularShelving = "Modular Shelving",
	OTRBridgingWall = "OTR Bridging Wall",
	OneDoor = "1 Door",
	OneDoorCombiWardrobe = "1 Door Combi Wardrobe",
	OneDoorSilverMirror = "1 Door Silver Mirror",
	OneDoorSmokedGlass = "1 Door Smoked Glass",
	OneDummyDrawer = "1 Dummy Drawer",
	Open = "Open",
	Shelving = "Shelving unit",
	SlidingWardrobe = "SlidingWardrobe",
	StableCorner = "Stable Corner",
	Standard = "Standard",
	ThreeDrawer = "3 Drawer",
	TwoDoor = "2 Door",
	TwoDoorCombiWardrobe = "2 Door Combi Wardrobe",
	TwoDoorSilverMirror = "2 Door Silver Mirror",
	TwoDoorSmokedGlass = "2 Door Smoked Glass",
	TwoDoor70To30Split = "2 Door 70-30 Split",
	TwoDrawer = "2 Drawer",
	Utility = "Utility",
	Vanity = "Vanity -",
	VanityAdjustable = "Vanity - Adjustable",
	WallLShape = "WallLShape",
	Wardrobe = "Wardrobe",
}


export enum UnitCategory {
	Base = "Base",
	Wall = "Wall",
	Universal = "Universal",
	Tower = "Tower",
	Island = "Island",
	Wardrobes = "Wardrobes",
	Bridging = "Bridging Units",
	Chests = "Chests",
}

export enum UnitSubCategory {
	Accessibility = "Accessibility",
	Angle = "Angle",
	Appliance = "Appliance",
	Bedside = "Bedside",
	Combi = "Combi",
	CooksPantry = "Cooks Pantry",
	Corner = "Corner",
	CurvedEnd = "Curved End",
	Drawer = "Drawer",
	FeatureAperture = "Feature Aperture",
	FeatureWall = "Feature Wall",
	Floating = "Floating",
	Hideaway = "Hideaway",
	Hob = "Hob",
	IndustrialAppliance = "Industrial Appliance",
	IndustrialWall = "Industrial Wall",
	InternalUnit = "Internal Unit",
	IroningUnit = "Ironing Unit",
	IslandEnd = "Island End",
	KneeDrawer = "Knee Drawer",
	LivingAndLounge = "Living and Lounge",
	Midway = "Midway",
	ModularShelving = "Modular Shelving",
	Peninsular = "Peninsular",
	PetBeds = "Pet Beds",
	Sink = "Sink",
	StableCorner = "Stable Corner",
	Standard = "Standard",
	Suspended = "Suspended",
	TopBox = "Top Box",
	TopBoxCorner = "Top Box Corner",
	UnderWardrobe = "Under Wardrobe",
	WalkIn = "Walk In",
}


export enum UnitModelType {
	ThousandShelving = "1000 Shelving (Flatpack)",
	SixHundredShelving = "600 Shelving (Flatpack)",
	CooksTables = "Cook's Tables",
	Door = "Door",
	OneDoor = "1 Door",
	OneDoorLH = "1 Door LH",
	OneDoorRH = "1 Door RH",
	FourDoorHideaway = "4 Door Hideaway",
	IslandEnd = "Island End",
	IslandEndWithTwoWineRack = "Island End with 2 Wine Rack",
	IslandEndWithWineRack = "Island End with Wine Rack",
	TwoDoor = "2 Door",
	LinearTwoDoor = "Linea 2 Door",
	Drawer = "Drawer",
	TwoDrawer = "2 Drawer",
	ThreeDrawer = "3 Drawer",
	FiveDrawerCrate = "5 Drawer Crate",
	LineaTwoDrawer = "Linea 2 Drawer",
	LineaThreeDrawer = "Linea 3 Drawer",
	OneDummyDrawer = "1 Dummy Drawer",
	PetBaseTop = "Pet Base Top",
	PetBaseBottom = "Pet Base Bottom",
	WineRack = "Wine Rack",
	TwoDrawerOneInternalDrawer = "2 Drawer + 1 Internal Drawer",
	ThreeDrawerDummyTopDrawer = "3 Drw Dummy Top Drawer",
	OneDrawerOneInternalDrawer = "1 Drawer + 1 Internal Drawer",
	OvermountBelfast = "Overmount Belfast",
	Linea3DrawerwithDummyDrawer = "Linea 3 Drawer with Dummy Drawer",
	ThreeDrawerWithDummyDrawer = "3 Drawer with Dummy Drawer",
	TwoDoorPlusDrawerPlusOneFullShelf = "2 Door + 1 Drawer + 1 Full Shelf",
	OneDoorPlusOneDrawerPlusOneFullShelf = "1 Door + 1 Drawer + 1 Full Shelf",
	OneDoorPlusOneHalfMidShelf = "1 Door + 1 Half Mid Shelf",
	TwoDoorPlusOneHalfMidShelf = "2 Door + 1 Half Mid Shelf",
	TwoDoorPlusOneX141DummyDrawer = "2 Door + 1x141 Dummy Drw",
	TwoBinPlusInternalDrawer = "600 2 Bin + Internal Drawer",
	WickerVegetableBasket = "Wicker Vegetable Basket",
	PullOutLaundryUnit = "Pull Out Laundry Unit",
	MetalVegetableBasket = "Metal Vegetable Basket",
	ThreeInternalDrawer = "3 Internal Drawer",
	FourDrawerWithDummyDrawer = "4 Drawer with Dummy Drawer",
	FiveDrawerWithDummyDrawer = "5 Drawer with Dummy Drawer",
	LineaPetBaseTop = "Linea Pet Base Top",
	LineaPetBaseBottom = "Linea Pet Base Bottom",
	MilanoPetBaseTop = "Milano Pet Base Top",
	MilanoPetBaseBottom = "Milano Pet Base Bottom",
	VogueFlatPackThreeDrwDummyTopDrawer = "Vogue Flat Pack 3 Drw Dummy Top Drawer",
	Hideaway5050 = "50-50 Hideaway",
	Hideaway7030 = "70-30 Hideaway",
	TwoBinWidth400 = "400 2 Bin",
	OneDoorShelfBase = "1 Full Shelf",
}


export enum UnitAvailability {
	Active = "Active",
	SemiRetired = "Inactive",
	Retired = "EndOfLife",
	Born = "UnderConstruction",
	Dead = "Dead",
	Conception = "Conception",
	Gestation = "Gestation",
}

export enum WorktopType {
	BreakfastBar = "Breakfast Bar",
	Worktop = "Worktop",
	ButchersBlock = "Butcher’s Block",
	"Pastry Slab" = "Pastry Slab",
	Upstand = "Upstand",
	Downturn = "Downturn",
	WallCovering = "Wall Covering",
	Corner = "Corner",
	LShape = "L Shape",
	LShapeCorner = "L Shape Corner",
	LShapeCornerLH = "L Shape Corner LH",
	LShapeCornerRH = "L Shape Corner RH",
	InternalCurveCorner = "Internal Curve Corner",
	InternalCurveCornerLH = "Internal Curve Corner LH",
	InternalCurveCornerRH = "Internal Curve Corner RH",
	DiagonalCorner = "Diagonal Corner",
	DiagonalCornerLH = "Diagonal Corner LH",
	DiagonalCornerRH = "Diagonal Corner RH",
	DiagonalCornerEighteenInch = "Diagonal Corner (18 inch)",
	DiagonalCornerLHEighteenInch = "Diagonal Corner LH (18 inch)",
	DiagonalCornerRHEighteenInch = "Diagonal Corner RH (18 inch)",
	DropDownEndPanel = "Drop Down End Panel",
	Windowsill = "Windowsill",
	Hideaway = "Worktop Hideaway",
}

export enum LightingProductAttributes {
	PlinthLighting = "Plinth Light",
	UnderUnitLighting = "Under Unit Light",
	InteriorUnitLighting = "Interior Unit Light",
	DrawerLighting = "Drawer Light",
	MilanoProfileLighting = "Milano Profile Light",
	LightingGroup = "Lighting Group",
	LightingColour = "Lighting Colour",
	DriverType = "Driver Type",
	DriverRequired = "Driver Required",
	WattageOld = "WATTAGE",
	Wattage = "Wattage",
	Flexible = "Flexible",
	DiffuserRequired = "Diffuser Required",
	DriverPorts = "Driver Ports",
	AccessoryType = "Accessory Type",
	UpsellPackage = "Upsell Packages",
}

export enum ProductAttributes {
	ACCESSORY_TYPE = "Accessory Type",
	APPLIANCE_GROUP = "Appliance Group",
	BACKWARDS_LEVER_REACH = "Backwards Lever Reach",
	BED_SIZE = "Bed Size",
	BELFAST_SINK_LAMINATE_WORKTOPS_ALLOWED = "Belfast Sink - Laminate W/Tops Allowed",
	BELFAST_SINK_UNIT_REQUIRED = "Belfast Sink Unit Required",
	BOWL_CONFIGURATION = "Bowl Configuration",
	BOWL_1_EXTERNAL_LENGTH = "Bowl 1 External Length (mm)",
	BOWL_2_EXTERNAL_LENGTH = "Bowl 2 External Length (mm)",
	BUOH_RESTRICTIONS = "BUOH Restrictions",
	BURNER_HEIGHT_FROM_FLOOR = "Burner Height from Floor (mm)",
	CAPACITY_L = "Capacity (L)",
	CHILD_LOCK = "Child Lock",
	CERAMIC_HOB_RESTRICTION = "Ceramic Hob Restriction",
	CLEANING = "Cleaning",
	CONNECTION_TYPE = "Connection Type",
	CONTROL_POSITION = "Control Position",
	CONTROL_TYPE = "Control Type",
	COOKING_FUNCTIONS = "Cooking Functions",
	CORE_PRODUCT = "Core Product",
	COVERAGE = "Coverage (m2)",
	CUTOUT_DEPTH = "Cutout Depth (mm)",
	CUTOUT_WIDTH = "Cutout Width (mm)",
	CUTOUT_TYPE = "Cutout Type",
	CUT_OUT_TO_WALL_DISTANCE = "Cut Out to Wall Distance",
	DOOR_SPLIT = "Door Split",
	DOWNDRAFTHOOD_FASCIA_DEPTH = "Downdraft Fascia Depth (mm)",
	DEPTH_AVAILABILITIES = "Depth Availabilities",
	DRAINER_CONFIGURATION = "Drainer Type",
	DRAINER_INSTALLATION_DEPTH = "Drainer Installation Depth",
	DRAWER_BOX_TYPE = "Drawer Box Type",
	DRAWER_UNIT_RESTRICTIONS = "Drawer Unit Restrictions",
	DRIVER_REQUIRED = "Driver Required",
	ENERGY_RATING = "Energy Rating",
	EXTRACTION_TYPE = "Extraction Type",
	EXTRACTOR_DISTANCE_FROM_ELECTRIC_COOKING_SURFACE = "Extractor - Distance required from electric cooking surface",
	EXTRACTOR_DISTANCE_FROM_GAS_COOKING_SURFACE = "Extractor - Distance required from gas cooking surface",
	FILTER_INCLUDED = "Filter Included",
	FINISH = "Finish",
	FRONTAL_DOOR_OPTION = "Frontal Door Option",
	FITTING_STYLE = "Fitting Style",
	FLEXI_ZONE = "Flexi Zone",
	FUEL_TYPE = "Fuel type",
	GAS_HOB_RESTRICTION = "Gas Hob Restrictions",
	GLASS_WALL_MIN_LENGTH = "Glass Wall - Min Length (mm)",
	GLASS_WALL_MIN_WIDTH = "Glass Wall - Min Width (mm)",
	GRILL = "Grill",
	GUARANTEE = "Guarantee",
	HANDLE_POSITIONING_GROUP = "Handle Positioning Group",
	HOB_2_HOOD = "Hob 2 Hood",
	HOB_TYPE = "Hob Type",
	INDUCTION_HOB_RESTRICTION = "Induction Hob Restriction",
	INSTALLATION_DEPTH = "Installation Depth",
	INTERGRATED_HANDLE_COLOUR = "Integrated Handle Colour",
	INDUSTRIAL_APPLIANCE_APERTURE_RESTRICTIONS = "Industrial Appliance Aperture Restrictions",
	LARGE_DELIVERY_ITEM = "Large Delivery Item",
	LIGHTING_TEMPERATURE = "Lighting Temperature",
	MAX_EXTRACTION_RATE = "Maximum Extraction Rate",
	MAXIMUM_MICROWAVE_POWER = "Maximum Microwave Power (W)",
	MICROWAVE_FUNCTIONS = "Microwave Functions",
	MINIMUM_CABINET_WIDTH_OVERMOUNT = "Minimum Cabinet Width (mm) - Overmount",
	MINIMUM_CABINET_WIDTH_UNDERMOUNT = "Minimum Cabinet Width (mm) - Undermount",
	MINIMUM_TAP_REACH_REQUIRED_MM = "Minimum Tap Reach Required (mm)",
	MOUNTING_TYPE = "Mounting Type",
	NOISE_LEVEL = "Noise Level (dB)",
	NUMBER_OF_HOBS_OR_BURNERS = "Number of Zones/Burners",
	NUMBER_OF_POWER_LEVELS = "Number of Power Levels",
	OVEN_TYPE = "Oven Type",
	PATTERNED_WORKTOPS = "Patterned Worktops",
	PLANNED_ABOVE_AN_OVEN_ONLY = "Planned above an oven only",
	PLANNER_CATEGORY = "Planner Category",
	POINT_OF_INTEREST = "Point Of Interest",
	PLINTH_CUT_OUT_REQUIRED = "Plinth Cut Out Required",
	PRIMARY_COLOUR_GROUP = "Primary colour group",
	PRODUCT_MATERIAL = "Product Material",
	RANGE_COOKER_VOID = "Range Cooker Void (mm)",
	RESIDUAL_HEAT_INDICATOR = "Residual Heat Indicator",
	RESTRICT_REMOVAL_FROM_BASKET = "Restrict Removal From Basket",
	RETAIL_CAPTION = "Retail Caption",
	ROTARY_PLATE = "Rotary Plate",
	SafetyZoneA = "Safety Zone A",
	SafetyZoneB = "Safety Zone B",
	SafetyZoneC = "Safety Zone C",
	SafetyZoneD = "Safety Zone D",
	SafetyZoneE = "Safety Zone E",
	SINK_CUT_OUT_DEPTH = "Sink Cut-Out Depth (mm)",
	SINK_CUT_OUT_WIDTH = "Sink Cut-Out Width (mm)",
	SPECIAL_ORDER_PRODUCT = "Special Order Product",
	SPECIALIST_DELIVERY_APPLIANCE = "Specialist Delivery Appliance",
	SPECIALIST_WORKTOP_RESTRICTIONS = "Specialist Worktop Restrictions",
	SUPPORT_TYPE = "Support Type",
	TAP_HOLES = "Tap Holes",
	TAP_HOLES_REQUIRED = "Tap Holes Required",
	TAP_REACH_MM = "Tap Reach (mm)",
	TELESCOPIC_RAILS = "Telescopic Rails",
	UNAVAILABLE_WITH_RECESSED_DRAINER = "Unavailable with Recessed Drainers",
	UNSUITABLE_FOR_CERAMIC = "Unsuitable For Ceramic",
	UNSUITABLE_FOR_BELFAST_SINKS = "Unsuitable For Belfast Sinks",
	VENTILATION_TYPE = "Ventilation Type",
	WARRANTY_LABOUR = "Warranty - Labour",
	WARRANTY_PARTS = "Warranty - Parts",
	WASHABLE_FILTER = "Washable Filter",
	WASTE_HOLES = "Waste Holes",
	WOK_BURNER = "Wok Burner",
}


export enum WidgetGroupTypes {
	accessibility = "Accessibility Combination",
	bayWindow = "Bay Window",
	canopy = "Canopy Extractor",
	combiChest = "Combi Chest",
	combiWardrobe = "Combi Wardrobe",
	cornerBlock = "Corner Block",
	default = "Unknown Combination",
	downdraft = "Downdraft Extractor",
	featureApertureTower = "Feature Aperture Tower",
	hideawayKitchens = "Hideaway Kitchens",
	hideawayUtility = "Hideaway Utility",
	industrialIslandBlock = "Industrial Island Block",
	industrialTowerBlock = "Industrial Tower Block",
	island = "Island",
	mantel = "Mantel Combination",
	microwaveHoodCombo = "Microwave Hood Combo",
	panelReadyRefrigerator = "Panel Ready Refrigerator",
	peninsular = "Peninsular Combination",
	petBed = "Pet Bed",
	provenceIsland = "Provence Island",
	stableCorner = "Stable Corner",
	stackedWardrobe = "Stacked Wardrobe",
	ventingHob = "Venting Hob",
}

export enum NoteTypes {
	DesignerNote = "Designer Notes",
	SurveyorNote = "Surveyor Notes",
	InstallerNote = "Installer Notes",
	PlanNote = "Plan Notes",
	SupplyNote = "Supply Notes",
	Alert = "Alert",
	DeclinedItemsNote = "Declined Items Notes",
	SpecialistWorktopNote = "Specialist Worktop Notes",
	SupplementaryWorkNote = "Supplementary Works Notes",
	Hidden = "Hidden",
}

export enum AccessoryType {
	AccessibilityWallAccessory = "Accessibility Wall",
	Adhesives = "Adhesives",
	IndustrialIslandUnitSpacer = "Industrial Island Unit Spacer",
	LEDMotionSwitch = "LED Motion Switch",
	MitrePenAndAdhesive = "Mitre Pen and Adhesive",
	MilanoApplianceHousingFixing = "Milano Appliance Housing Fixing",
	MitrePlinthConnector18 = "Mitre Plinth Connector (18mm)",
	MitrePlinthConnector1920 = "Mitre Plinth Connector (19mm/20mm)",
	MitrePlinthConnector2122 = "Mitre Plinth Connector (21mm/22mm)",
	PanelReadyRefrigeratorJoinKitHandleToHandle = "1 Door Panel Ready Refrigerator - Handle to Handle Join Kit",
	PanelReadyRefrigeratorJoinKitHingeToHandle = "1 Door Panel Ready Refrigerator - Hinge to Handle Join Kit",
	PanelReadyRefrigeratorJoinKitHandleToHinge = "1 Door Panel Ready Refrigerator - Handle to Hinge Join Kit",
	Mortars = "Mortars",
	PeninsularFittingPack = "Peninsular Fitting Pack",
	Spacers = "Spacers",
	TekBrickCorner = "Tek Brick Corner",
	PlinthVent = "Plinth Vent",
	HeatReflectiveTape = "Heat Reflective Tape",
}

export enum BowlConfiguration {
	HalfBowl = "0.5 Bowl",
	SingleBowl = "1 Bowl",
	RoundBowl = "1 Bowl Round",
	ExtraBowl = "1.5 Bowl",
	DoubleBowl = "2 Bowl",
}

export enum AmpConnectionTypes {
	AmpSupply13 = "13 Amp Supply",
}

export enum CutoutType {
	PopUpSocket = "Pop Up Socket",
	AirSwitch = "Air Switch",
}

export enum DrainerType {
	LeftHandDrainer = "Left Hand Drainer",
	RightHandDrainer = "Right Hand Drainer",
	Reversible = "Reversible",
	None = "None",
	Drainer = "Drainer",
}

export enum DrawerBoxType {
	Grass = "Grass",
	Taiming = "Taiming",
}

export enum DepthAvailabilities {
	Milano570 = "570_MILANO",
	Standard570 = "570_STANDARD",
	Milano620 = "620_MILANO",
	Standard620 = "620_STANDARD",
}

export enum VentilationTypes {
	Vented = "Vented",
	Condenser = "Condenser",
}

export enum HandlePositioningGroup {
	Sarah = "Sarah",
}

export enum MountingType {
	Undermount = "Undermount",
	Overmount = "Overmount",
	OvermountAndUndermount = "Overmount and Undermount",
}

export enum ExtractionTypes {
	Ducted = "Ducted",
	Recirculated = "Recirculated",
	DuctedAndRecirculated = "Ducted & Recirculated",
}

export enum FuelTypes {
	Dual = "Dual Fuel",
	Electric = "Electric",
	Gas = "Gas",
	Oil = "Oil",
}

export enum RangeStateHandles {
	Active = "Active",
	Dead = "Dead",
	Retired = "EndOfLife",
	SemiRetired = "Inactive",
	Born = "UnderConstruction",
	Conception = "Conception",
	Gestation = "Gestation",
	BothActiveAndSemiRetired = "BothActiveAndSemiRetired",
}

export enum StoreHandles {
	SINKS_AND_TAPS = "SINKS_AND_TAPS",
	CORNICE_PLINTH_AND_PELMETS = "CORNICE,_PLINTH_AND_PELMETS",
	HANDLES = "HANDLES",
	FINISHING_TOUCHES = "FINISHING_TOUCHES",
	APPLIANCES = "APPLIANCES",
	FLOORING = "FLOORING",
	BEDS = "BEDS",
	SPARE_PARTS = "SPARE_PARTS",
	FINISHING_TOUCHES_EXTRA = "FINISHING_TOUCHES_(EXTRA)",
	COMPONENTS = "COMPONENTS",
	LIGHTING = "LIGHTING",
	TABLES_AND_SEATING = "TABLES_AND_SEATING",
	WALL_COVERINGS = "WALL_COVERINGS",
	WORKTOPS = "WORKTOPS",
	BEDS_AND_MATTRESSES = "BEDS_AND_MATTRESSES",
}

export enum ProductStateHandle {
	Active = "Active",
	SemiRetired = "SemiRetired",
	Retired = "Inactive",
	Dead = "Dead",
	Conception = "Conception",
	Gestation = "Gestation",
	Born = "UnderConstruction",
}

export enum ProductSubcategories {
	AmericanStyleFridgeFreezers = "American Style Fridge Freezers",
	BelfastSinks = "Belfast Sinks",
	BuiltInBeerDispensers = "Built In Beer Dispensers",
	BuiltInCoffeeMachines = "Built In Coffee Machines",
	BuiltInMicrowaves = "Built In Microwaves",
	BuiltUnderDoubleOvens = "Built Under Double Ovens",
	BuiltUnderFreezers = "Built Under Freezers",
	BuiltUnderFridges = "Built Under Fridges",
	CeramicHobs = "Ceramic Hobs",
	ChimneyHoods = "Chimney Hoods",
	CombiMicrowaves = "Combi Microwaves",
	CompactOvens = "Compact Ovens",
	DoubleOvens = "Double Ovens",
	DowndraftHoods = "Downdraft Hoods",
	DecorEnds = "Decor Ends",
	Drainers = "Drainers",
	DualMountSinks = "Dual Mount Sinks",
	FarmhouseSinks = "Farmhouse Sinks",
	FourInOneTaps = "4 In 1 Taps",
	FreeStandingDryer = "Free Standing Dryer",
	FreeStandingFridgeFreezers = "Free Standing Fridge Freezers",
	FreeStandingFridges = "Free Standing Fridges",
	FreeStandingWineCoolers = "Free Standing Wine Coolers",
	FreestandingDishwashers = "Freestanding Dishwashers",
	FreestandingFreezers = "Freestanding Freezers",
	FreestandingWasherDryers = "Freestanding Washer Dryers",
	FreestandingWashingMachines = "Freestanding Washing Machines",
	GasHobs = "Gas Hobs",
	HotWaterTaps = "Hot Water Taps",
	InductionHobs = "Induction Hobs",
	IntegratedDishwashers = "Integrated Dishwashers",
	IntegratedDryers = "Integrated Dryers",
	IntegratedFridgeFreezers = "Integrated Fridge Freezers",
	IntegratedHoods = "Integrated Hoods",
	IntegratedWasherDryers = "Integrated Washer Dryers",
	IntegratedWashingMachines = "Integrated Washing Machines",
	IntegratedWineCoolers = "Integrated Wine Coolers",
	IslandHoods = "Island Hoods",
	ModularFrame = "Modular Frame",
	ModularShelving = "Modular Shelving",
	PanelReadyRefrigerator = "1 Door Panel Ready",
	OvermountSinks = "Overmount Sinks",
	RangeCookers = "Range Cookers",
	SemiIntegratedDishwashers = "Semi-Integrated Dishwashers",
	Shelving = "Shelving",
	SingleOvens = "Single Ovens",
	SpecialityTaps = "Speciality Taps",
	SpotLighting = "Spot Lighting",
	StandardTaps = "Standard Taps",
	StorageDrawers = "Storage Drawers",
	StripLighting = "Strip Lighting",
	ThreeInOneTaps = "3 In 1 Taps",
	TowerFreezers = "Tower Freezers",
	TowerFridges = "Tower Fridges",
	UndermountSinks = "Undermount Sinks",
	VentingHobs = "Venting Hobs",
	WallMicrowaves = "Wall Microwaves",
	WallMountedTaps = "Wall Mounted Taps",
	WarmingDrawers = "Warming Drawers",
	WasteDisposal = "Waste Disposal",
	IslandGlassShelving = "Island Glass Shelving",
	Fittings = "Fittings",
	Flooring = "Flooring",
	IslandEndLegs = "Island End Legs",
	IslandInternalLegs = "Island Internal Legs",
	TowerGlassShelving = "Tower Glass Shelving",
	TowerEndLegs = "Tower End Legs",
	TowerInternalLegs = "Tower Internal Legs",
	IslandEndFrame = "Island End Frame",
	IslandInternalFrame = "Island Internal Frame",
	TowerEndFrame = "Tower End Frame",
	TowerInternalFrame = "Tower Internal Frame",
	CeramicSinks = "Ceramic Sinks",
	CutleryInserts = "Cutlery Inserts",
	TekGlass = "Tek Glass",
	TekBrick = "Tek Brick",
	TekWall = "Tek Wall",
	TekBrickAccessories = "Tek Brick Accessories",
	BaseTopProfile = "Base Top Profile",
	BaseMidProfile = "Base Mid Profile",
	VacuumSealers = "Vacuum Sealers",
	PlinthHeating = "PlinthHeating",
}

export enum LightingPlanModelKeys {
	UnitLighting = "unitLighting",
	LightingSelections = "lightingSelections",
	ThroughSubMenusLightingType = "throughSubMenusLightingType",
	RunQuantities = "runQuantities",
}

export enum WorktopTabKeys {
	Material = "material",
	SurfaceColour = "surfaceColour",
	EdgeColour = "edgeColour",
	Thickness = "thickness",
	Profile = "profile",
	TimberAreaSurfaceColour = "timberAreaSurfaceColour",
	TimberAreaThickness = "timberAreaThickness",
	TimberAreaProfile = "timberAreaProfile",
}

export enum LightingDriverType {
	Smart = "Smart",
	Standard = "Standard",
	ColourChanging = "Colour Changing",
}

export enum LightingColourType {
	WarmWhite = "Warm White",
	NaturalWhite = "Natural White",
	CoolWhite = "Cool White",
	ColourChanging = "Colour Changing",
	Tunable = "Tunable",
}

export type DoorType = "left" | "right";

export enum FrontendRoomHandle {
	Kitchen = "kitchens",
	Bedroom = "BEDROOM_2022",
}

export enum RoomLocation {
	Original = "Original",
	New = "New",
}

export enum ProductItemTypes {
	CHEST_TOP = "CHEST_TOP",
	STANDARD = "STANDARD",
	WALL_COVERING = "WALL_COVERING",
	WORKTOP = "WORKTOP",
}

export enum ProductRelationTypeHandle {
	Recommended = "RECOMMENDED",
	Related = "RELATED",
	Incompatible = "INCOMPATIBLE",
	StyleMatch = "STYLE_MATCH",
	Walls = "WallAccessories",
	Spares = "SPARES",
}

export enum ShowroomVisibilityAvailability {
	Hidden = "HIDDEN",
	Available = "AVAILABLE",
}

export const infoAreaDescriptions = [
	"Overview",
	"Technical",
	"Design",
	"Feature",
	"Function",
	"Additional",
	"Warranty"
] as const;